"""Quality gates for deterministic and AI-enhanced slide content."""

from __future__ import annotations

from .errors import ErrorCode, HackLuminaryError


BANNED_PHRASES = {
    "as an ai",
    "generated by ai",
    "revolutionary",
    "game-changing",
    "world-class",
    "best-in-class",
}

UNSUPPORTED_CLAIMS = {
    "guarantees",
    "always",
    "never fails",
    "perfect",
    "100%",
}


def _slide_text(slide: dict) -> str:
    parts = [
        str(slide.get("title", "")),
        str(slide.get("subtitle", "")),
        str(slide.get("content", "")),
    ]

    items = slide.get("list_items", [])
    if isinstance(items, list):
        parts.extend(str(item) for item in items)

    return "\n".join(parts)


def evaluate_quality(slides: list[dict]) -> dict:
    """Return machine-readable quality report and gate status."""

    errors: list[str] = []
    warnings: list[str] = []

    content_slides = [s for s in slides if s.get("type") not in {"title", "closing"}]
    with_evidence = 0

    for slide in slides:
        text = _slide_text(slide)
        text_lower = text.lower()
        slide_id = slide.get("id", slide.get("type", "slide"))

        if slide.get("type") not in {"title", "closing"}:
            refs = slide.get("evidence_refs", [])
            if refs:
                with_evidence += 1
            else:
                errors.append(f"Slide '{slide_id}' has no evidence references.")

        for phrase in sorted(BANNED_PHRASES):
            if phrase in text_lower:
                errors.append(f"Slide '{slide_id}' contains banned phrase: '{phrase}'.")

        for claim in sorted(UNSUPPORTED_CLAIMS):
            if claim in text_lower and not slide.get("evidence_refs"):
                errors.append(f"Slide '{slide_id}' includes unsupported claim '{claim}' without evidence.")

        if "i built" in text_lower or "we built" in text_lower:
            warnings.append(
                f"Slide '{slide_id}' uses first-person ownership language; verify factual accuracy."
            )

    coverage = 1.0
    if content_slides:
        coverage = with_evidence / len(content_slides)

    if coverage < 0.8:
        errors.append(
            f"Evidence coverage {coverage:.2f} is below minimum threshold 0.80 for non-title slides."
        )

    status = "pass" if not errors else "fail"
    return {
        "status": status,
        "errors": errors,
        "warnings": warnings,
        "metrics": {
            "slide_count": len(slides),
            "content_slide_count": len(content_slides),
            "evidence_coverage": round(coverage, 3),
        },
    }


def enforce_quality(report: dict, strict: bool) -> None:
    if strict and report.get("status") == "fail":
        first = report.get("errors", ["Quality gate failed."])[0]
        raise HackLuminaryError(
            ErrorCode.QUALITY_GATE_FAILED,
            "Quality gate failed.",
            hint=first,
        )
